project:
  type: website
  output-dir: docs

website:
  title: "Primeras pruebas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Otraventan.qmd
      - about.qmd

format:
  html:
    theme: Darkly
    mainfont: Montserrat
    fontsize: 1.3rem
    fontcolor: "white"
    css: styles.css
    toc: true

editor: visual

